# Generated by Django 5.1.7 on 2025-04-28 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_employee_payhistory_delete_payentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOffBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_days', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('sick_days', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('personal_days', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_off_balance', to='payroll.employee')),
            ],
        ),
    ]
